@extends('layouts.app')

@section('content')
    <h1>About Backchannel.education</h1>
    <p>This site was created by me - Dr. Mark Samberg, and educator, educational technology specialist, and technology director in North Carolina.In my classroom, I was an avid user of a tool called Today'sMeet which, sadly, <a href="https://web.archive.org/web/20180601171403/http://blog.todaysmeet.com/thank-you-and-goodbye/" target="_blank">shut down in 2018</a>. Before the pandemic and Zoom chats, TodaysMeet served a very similar purpose to the chat - allowing side conversations about the presentation that students were following in the room. While other tools have come and gone, none has ever worked as well as the original TodaysMeet that James Socol created. So I set out to recreate it for my own use, and create something that hopefully others can find useful as well.</p>
    <p>Like TodaysMeet, Backchannel.education is a resource for educators to facilitate these deeper conversations in the context of a presentation or lesson in the classroom. Use it for side conversations, bellringers and exit tickets, collecting student feedback, pulse checks, as a safer option for group projects and team meetings, for office hours - the possibilities are endless!</p>
    <p>It's not my intention to rip off another creator's work. James Socol's creation changed the way I taught and facilitated professional learning, so I created a tool that will allow me to continue that work (though a few years late, thanks COVID). I do not intend this site to be a moneymaking adventure for me, nor a full-time gig. Running this site isn't free and <a href="https://ko-fi.com/mjsamberg" target="_blank">donations to offset those costs are certainly welcome</a>, but the site will always be free for educators to use with no restrictions or paid tiers. You may see a few new features, but my goal with this site is to do one thing and do it well, quickly, and reliably.</p>
    <p>My own website is still woefully under construction. I've stopped actively engaging with Twitter but I'm on Mastodon at <a href="https://hachyderm.io/@mjsamberg" target="_blank">mjsamberg@hachyderm.io</a>.</p>
@endsection
